### ISSUE TITLE
User input

### ISSUE THREAD

**Issue by Sreyasi** [chengwill97/SANDI-Interactive-Demo#19]
1. Take user input for number of images to be included - a check-box for "all" and a text box to enter a number

**Comment by chengwill97** [comment]
> 1. ~~Take user input for number of images to be included - a check-box for "all" and a text box to enter a number~~

I gave the user a single textbox and the default for the textbox would be to include all images instead of having to use another check-box to do so. Also, I set the minimum number of images to use as 0, max number of images (arbitrarily) as 9001, and step number as 1.

**Comment by Sreyasi** [comment]
Hey I found the error in the code. 
Are you able to compile the code yourself? In that case I can point you to the error.
Otherwise I can compile it and send you the jar file.

Also, i think it's better to focus on the servlet at the moment. This can be fixed later.

**Comment by chengwill97** [comment]
> Hey I found the error in the code.
> Are you able to compile the code yourself? In that case I can point you to the error.
> Otherwise I can compile it and send you the jar file.
> 
> Also, i think it's better to focus on the servlet at the moment. This can be fixed later.

Would you be able to tell me the instructions to compile it? I can try to compile the jar.

**Comment by chengwill97** [comment]
The issue has been fixed now.
