### ISSUE TITLE
Image Tags

### ISSUE THREAD

**Issue by chengwill97** [chengwill97/SANDI-Interactive-Demo#9]
1. ~~Instead of "Missing Tags" say something like "Sorry we couldn't identify objects in the following images. Please help."~~
2. ~~Give some example tags - for e.g., each box can show "person, ball, park"~~

**Comment by chengwill97** [comment]
I added examples of input boxes and explanations

**Comment by Sreyasi** [comment]
User tags need not be one-word.
For multi-word tags, post-process to replace spaces with underscore

**Comment by Sreyasi** [comment]
1. Lower YOLO threshold.
2. Incorporate scene detection (get caffe running).
3. Incorporate google tags. Google has a restriction of 100 queries from one IP per day. There needs to be a check for this. The entire application must not crash if this limit is reached. It should simple run without the Google tags.

**Comment by chengwill97** [comment]
> 1. ~~ Lower YOLO threshold. ~~
> 2. Incorporate scene detection (get caffe running).
> 3. Incorporate google tags. Google has a restriction of 100 queries from one IP per day. There needs to be a check for this. The entire application must not crash if this limit is reached. It should simple run without the Google tags.

Lowered YOLO threshold to 0.25, and I fixed the disappearance of quotes

**Comment by chengwill97** [comment]
> ~~User tags need not be one-word.~~
> ~~For multi-word tags, post-process to replace spaces with underscore~~

Done

**Comment by chengwill97** [comment]
> > User tags need not be one-word.
> > For multi-word tags, post-process to replace spaces with underscore
> 
> Done
> 
> "Please help by filling in single or multi-word descriptions for each image."
> We don't really want descriptions, just tags. So perhaps something like "Please help by filling in concepts you see in the image" would be better.
> In the examples, "blue sky, relaxing vacation" is perfect. Just add an explicit object too, e.g. "building"

Okay, I changed it.

**Comment by chengwill97** [comment]
> 1. Lower YOLO threshold.
> 2. Incorporate scene detection (get caffe running).
> 3. Incorporate google tags. Google has a restriction of 100 queries from one IP per day. There needs to be a check for this. The entire application must not crash if this limit is reached. It should simple run without the Google tags.

I moved 2 and 3 to a new issue with the **feature** tag.
